# Generated by Django 5.1.5 on 2025-02-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduleCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("engineering", "工学部"),
                            ("science", "理学部"),
                            ("literature", "文学部"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "easy_level",
                    models.IntegerField(choices=[(1, "楽単"), (2, "落胆"), (3, "落単")]),
                ),
                ("required", models.BooleanField(default=True)),
            ],
        ),
    ]
