# Generated by Django 5.1.5 on 2025-02-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulecriteria",
            name="department_priority",
            field=models.IntegerField(
                choices=[(1, "絶対"), (2, "あればよし"), (3, "なくてよい")], default=2
            ),
        ),
        migrations.AddField(
            model_name="schedulecriteria",
            name="easy_level_priority",
            field=models.IntegerField(
                choices=[(1, "絶対"), (2, "あればよし"), (3, "なくてよい")], default=2
            ),
        ),
        migrations.AddField(
            model_name="schedulecriteria",
            name="required_priority",
            field=models.IntegerField(
                choices=[(1, "絶対"), (2, "あればよし"), (3, "なくてよい")], default=2
            ),
        ),
    ]
