# Generated by Django 5.1.5 on 2025-02-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0002_schedulecriteria_department_priority_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulecriteria",
            name="department_priority",
            field=models.IntegerField(
                choices=[(1, "絶対"), (2, "あればよし"), (3, "なくてよい")], default=3
            ),
        ),
        migrations.AlterField(
            model_name="schedulecriteria",
            name="easy_level_priority",
            field=models.IntegerField(
                choices=[(1, "絶対"), (2, "あればよし"), (3, "なくてよい")], default=3
            ),
        ),
        migrations.AlterField(
            model_name="schedulecriteria",
            name="required_priority",
            field=models.IntegerField(
                choices=[(1, "絶対"), (2, "あればよし"), (3, "なくてよい")], default=1
            ),
        ),
    ]
