# Generated by Django 5.1.5 on 2025-02-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0003_alter_schedulecriteria_department_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulecriteria",
            name="a_group_limit",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="schedulecriteria",
            name="b_group_limit",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="schedulecriteria",
            name="c_group_limit",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="schedulecriteria",
            name="content_type",
            field=models.CharField(
                choices=[("report", "レポート"), ("attendance", "出席"), ("test", "テスト")],
                default="attendance",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="schedulecriteria",
            name="excluded_periods",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="schedulecriteria",
            name="full_day_off",
            field=models.IntegerField(
                choices=[(1, "1日"), (2, "2日"), (3, "3日"), (4, "4日"), (5, "5日")],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="schedulecriteria",
            name="has_empty_slots",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schedulecriteria",
            name="is_audio_priority",
            field=models.BooleanField(default=False),
        ),
    ]
