# Generated by Django 5.1.5 on 2025-02-03 03:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0004_schedulecriteria_a_group_limit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedulecriteria",
            old_name="is_audio_priority",
            new_name="is_ondemand_priority",
        ),
    ]
