# Generated by Django 5.1.5 on 2025-02-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "scheduler",
            "0005_rename_is_audio_priority_schedulecriteria_is_ondemand_priority",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulecriteria",
            name="grade",
            field=models.IntegerField(
                choices=[(1, "1年"), (2, "2年"), (3, "3年"), (4, "4年")], default=1
            ),
        ),
        migrations.AddField(
            model_name="schedulecriteria",
            name="semester",
            field=models.CharField(
                choices=[("spring", "春"), ("autumn", "秋")],
                default="spring",
                max_length=10,
            ),
        ),
    ]
