# Generated by Django 5.1.5 on 2025-02-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0006_schedulecriteria_grade_schedulecriteria_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulecriteria",
            name="semester",
            field=models.CharField(
                choices=[("spring", "春"), ("autumn", "秋")], max_length=10
            ),
        ),
    ]
