# Generated by Django 5.1.5 on 2025-02-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0007_alter_schedulecriteria_semester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedulecriteria",
            name="department_priority",
        ),
        migrations.AddField(
            model_name="schedulecriteria",
            name="faculty",
            field=models.CharField(
                choices=[("fundamental", "基幹"), ("advanced", "先進"), ("creative", "創造")],
                default="fundamental",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="schedulecriteria",
            name="department",
            field=models.CharField(
                choices=[
                    ("mathematics", "数学"),
                    ("intermedia", "表現"),
                    ("chemistry", "化学"),
                ],
                max_length=50,
            ),
        ),
    ]
