# Generated by Django 5.1.5 on 2025-02-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0008_remove_schedulecriteria_department_priority_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulecriteria",
            name="department",
            field=models.CharField(
                choices=[
                    ("mathematics", "数学"),
                    ("intermedia", "表現"),
                    ("chemistry", "化学"),
                ],
                default="mathematics",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="schedulecriteria",
            name="easy_level",
            field=models.IntegerField(
                choices=[(1, "楽単"), (2, "落胆"), (3, "落単")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="schedulecriteria",
            name="easy_level_priority",
            field=models.IntegerField(
                choices=[(1, "絶対"), (2, "優先"), (3, "おまかせ")], default=3
            ),
        ),
        migrations.AlterField(
            model_name="schedulecriteria",
            name="required_priority",
            field=models.IntegerField(
                choices=[(1, "絶対"), (2, "優先"), (3, "おまかせ")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="schedulecriteria",
            name="semester",
            field=models.CharField(
                choices=[("spring", "春"), ("autumn", "秋")],
                default="spring",
                max_length=10,
            ),
        ),
    ]
