# Generated by Django 5.1.5 on 2025-02-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0009_alter_schedulecriteria_department_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedulecriteria",
            name="content_type",
        ),
        migrations.AddField(
            model_name="schedulecriteria",
            name="attendance_priority",
            field=models.IntegerField(
                choices=[(1, "最優先"), (2, "優先"), (3, "考慮せず")], default=1
            ),
        ),
        migrations.AddField(
            model_name="schedulecriteria",
            name="report_priority",
            field=models.IntegerField(
                choices=[(1, "最優先"), (2, "優先"), (3, "考慮せず")], default=2
            ),
        ),
        migrations.AddField(
            model_name="schedulecriteria",
            name="test_priority",
            field=models.IntegerField(
                choices=[(1, "最優先"), (2, "優先"), (3, "考慮せず")], default=3
            ),
        ),
        migrations.AlterField(
            model_name="schedulecriteria",
            name="easy_level_priority",
            field=models.IntegerField(
                choices=[(1, "最優先"), (2, "優先"), (3, "考慮せず")], default=3
            ),
        ),
        migrations.AlterField(
            model_name="schedulecriteria",
            name="required_priority",
            field=models.IntegerField(
                choices=[(1, "最優先"), (2, "優先"), (3, "考慮せず")], default=1
            ),
        ),
    ]
