# Generated by Django 5.1.5 on 2025-02-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0010_remove_schedulecriteria_content_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedulecriteria",
            name="required_priority",
        ),
        migrations.AlterField(
            model_name="schedulecriteria",
            name="a_group_limit",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="schedulecriteria",
            name="b_group_limit",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="schedulecriteria",
            name="c_group_limit",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="schedulecriteria",
            name="full_day_off",
            field=models.IntegerField(
                choices=[
                    (0, "0日"),
                    (1, "1日"),
                    (2, "2日"),
                    (3, "3日"),
                    (4, "4日"),
                    (5, "5日"),
                ],
                default=1,
            ),
        ),
    ]
